services:
  flask-server:
    build:
      context: ./RAG_backend
    container_name: flask-server
    ports:
      - "8090:8090" 
  react_app:
    build:
      context: ./react_app
    ports:
      - "9000:9000"
    depends_on:
      - flask-server